title: osrs_gph.rs back-end settings file.

api:
  url: https://prices.runescape.wiki/api/v1/osrs
  timespan: latest
  auth_headers:
    User-Agent: profit_margins - @blamblamdan

filepaths:
  price_data: api_data/price_data.json

  lookup_data:
    id_to_name: lookup_data/id_to_name.yaml
    name_to_id: lookup_data/name_to_id.yaml
    api_mapping: lookup_data/mapping.json

    recipes: lookup_data/recipes.yaml

  results:
    optimal: results/optimal_overview.md
    lookup: results/recipe_lookup.md

  main_log_file: runtime.log
  # TODO: Currently this is shared across all bin files
  bin_log_file: src/bin/generators.log

profit:
  # Underscores are removed from strings
  coins: 682_216
  percent_margin: 2.5
  weights:
    margin: 1.e-2
    time: -2.0
    gph: 1.e-5

  # Recipes will be ignored if any required items are listed here
  # (Items that have hit the buy limit or are just unwanted)
  ignore_items:
    -

display:
  # File output (Frontend)
  # Number of entries to display in optimal_overview (0 == all)
  number: 0 # For optimal_overview.md

  lookup: # For recipe_lookup.md
    # Number of entries from optimal_overview to lookup in recipe_lookup
    # (0 == None / Disabled)
    top: 3
    # Specific entries which might not be in the top bracket
    specific:
      - Smelting Steel Bars

  # Filtering results (Backend)
  must_profit: true
  show_hidden: false
  reverse: true

levels:
  # Put all player character levels here
  options:
    strict_recommended: true
  levels:
    combat level: 105
    quest points: 273
    attack: 87
    defence: 85
    strength: 80
    hitpoints: 85
    ranged: 74
    prayer: 70
    magic: 81
    cooking: 70
    woodcutting: 71
    fletching: 60
    fishing: 63
    firemaking: 83
    crafting: 82
    smithing: 71
    mining: 74
    herblore: 65
    agility: 71
    thieving: 77
    slayer: 75
    farming: 55
    runecraft: 59
    hunter: 59
    construction: 57
